WITH TEMP_TBL AS (
SELECT COUNT(ID_ALUNO) AS COUNT, CO_MUNICIPIO 
FROM CENSO.ALUNOS
WHERE TP_ETAPA_ENSINO = '41'
GROUP BY 2)
SELECT TEMP_TBL.COUNT, TEMP_TBL.CO_MUNICIPIO
FROM TEMP_TBL
ORDER BY 1 DESC
LIMIT 10;